-- ABAYO 0.7 launch persistence
-- Run once in the Supabase SQL Editor after taking a database backup.
-- The existing machines table is preserved; only deleted_at is added.

do $$
begin
    if to_regclass('public.machines') is null then
        raise exception 'ABAYO requires the existing public.machines table';
    end if;
end
$$;

alter table public.machines
    add column if not exists deleted_at timestamptz;

create index if not exists machines_deleted_at_idx
    on public.machines (deleted_at);

create table if not exists public.knowledge_documents (
    name text primary key,
    payload jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create or replace function public.set_abayo_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    new.updated_at = timezone('utc', now());
    return new;
end;
$$;

drop trigger if exists set_knowledge_documents_updated_at
    on public.knowledge_documents;
create trigger set_knowledge_documents_updated_at
before update on public.knowledge_documents
for each row execute function public.set_abayo_updated_at();

create table if not exists public.machine_hmi_profiles (
    id bigint generated by default as identity primary key,
    machine_id text not null,
    profile_name text not null,
    recipe_name text not null default '',
    source_type text not null default 'Manual entry',
    source_file_name text,
    notes text not null default '',
    imported_by text not null default '',
    approval_status text not null default 'Draft'
        check (approval_status in ('Draft', 'Verified', 'Approved')),
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists machine_hmi_profiles_machine_id_idx
    on public.machine_hmi_profiles (machine_id, created_at desc);

create table if not exists public.machine_hmi_parameters (
    id bigint generated by default as identity primary key,
    profile_id bigint not null
        references public.machine_hmi_profiles(id) on delete cascade,
    parameter_name text not null,
    parameter_value text not null,
    unit text not null default '',
    hmi_page text not null default '',
    notes text not null default '',
    sequence_no integer not null default 1 check (sequence_no > 0),
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists machine_hmi_parameters_profile_id_idx
    on public.machine_hmi_parameters (profile_id, sequence_no);

-- These documents are accessed only by the server-side Supabase key stored in
-- Streamlit Secrets. No anonymous browser policy is created.
alter table public.knowledge_documents enable row level security;
alter table public.machine_hmi_profiles enable row level security;
alter table public.machine_hmi_parameters enable row level security;
